name: Spack buildcache update index

on: workflow_dispatch

env:
  SPACK_BACKTRACE: please

jobs:
  update-index:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup Spack
      uses: spack/setup-spack@v3

    - name: Update index
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: spack -e . buildcache update-index github-actions-buildcache
