name: Spack buildcache update index

on: workflow_dispatch

env:
  SPACK_BACKTRACE: please

jobs:
  update-index:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Setup Spack
      uses: spack/setup-spack@5ab3c91bdefffffad9a7e45d1d156146afebb3a7

    - name: Push packages and update index
      run: |
        spack mirror set --push --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" github-actions-buildcache
        spack buildcache update-index github-actions-buildcache
